### ISSUE TITLE
incorrect font handling

### ISSUE THREAD

**Issue by jaygray0919** [truett-software/SDL#9]
ZillaSlab is not declared correctly and does not render

* https://github.com/truett-software/story-structured-data-linter/blob/qa/docs/story/index.html#L2574

**Comment by truett-software** [comment]
We have fixed the Zilla Slab fonts declared in story

1. Checked the story structure documents
https://truett-projects.readthedocs.io/en/latest/__project-web-story-structure/32-font-combination/zilla-slab/font-style/index.html

2. Added missing "font-style — Zilla Slab" CSS element definitions in SDL story.
